name: aliyun_emas_ios
description: iOS implementation of the aliyun_emas plugin
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.2"

flutter:
  plugin:
    implements: aliyun_emas
    platforms:
      ios:
        pluginClass: AliyunEmasPlugin
        dartPluginClass: AliyunEmasIOS

dependencies:
  flutter:
    sdk: flutter
  aliyun_emas_platform_interface:
    path: ../aliyun_emas_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^3.1.0
