name: aliyun_emas

on:
  pull_request:
    paths:
      - ".github/workflows/aliyun_emas.yaml"
      - "aliyun_emas/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/aliyun_emas.yaml"
      - "aliyun_emas/**"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.3.2
      working_directory: aliyun_emas

  android:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: aliyun_emas/example

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "11"

      - uses: subosito/flutter-action@v2

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: AVD Cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-29

      - name: Cache AVD Snapshot
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Integration Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: flutter test integration_test
          working-directory: aliyun_emas/example

  ios:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: aliyun_emas/example

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Start Simulator
        run: open -a Simulator.app

      - name: Integration Tests
        run: flutter test integration_test -d iPhone
